name: Bit Merge

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  main-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BIT_CONFIG_ACCESS_TOKEN: ${{ secrets.BIT_ACCESS_TOKEN }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize Bit
        uses: bit-tasks/init@v3
        with:
          ws-dir: "."

      - name: Bit Tag and Export
        uses: bit-tasks/tag-export@v4
        with:
          build: true
